# Generated by Django 4.1.6 on 2023-05-10 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetails',
            fields=[
                ('pname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('images', models.ImageField(blank=True, upload_to='travelimages/')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('place', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('img', models.ImageField(blank=True, upload_to='travelimages/')),
            ],
        ),
        migrations.CreateModel(
            name='Register_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=2)),
                ('add', models.TextField(blank=True, max_length=250, null=True)),
                ('pin', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=300)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='travelapp.packagedetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.register_table')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('amount', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.register_table')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.register_table')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIN', models.DateField(blank=True, null=True)),
                ('checkOut', models.DateField(blank=True, null=True)),
                ('adult', models.IntegerField(blank=True, null=True)),
                ('kid', models.IntegerField(blank=True, null=True)),
                ('women', models.IntegerField(blank=True, null=True)),
                ('men', models.IntegerField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.packagedetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travelapp.register_table')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000)),
                ('reach', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(upload_to='travelimages/')),
                ('places', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelapp.places')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelapp.packagedetails')),
            ],
        ),
    ]
