# Generated by Django 4.1.6 on 2023-05-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_book_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='places',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='reach',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
